### ISSUE TITLE
send moods to light control node

### ISSUE THREAD

**Issue by Jan21493** [mjwwit/node-red-contrib-ikea-tradfri#25]
I've just started with node red, so maybe there is something I have missed or overlooked, but when I've created my first nodes to connect Loxone home automation with some IKEA tradfri lights it did not fully worked as expected. To narrow down the problem, I've created a simple test flow (see below) to reproduce the issue: 

If I only change color (EDIT: must be _brightness_) OR _color temperature_, everything works fine. If I change BOTH at the same time with the moods provided in the example, the first push only changes the color temperature and I have to push the inject node again to change the brightness.

<details>
  <summary>Example code to replicate problem</summary>
  
```yaml
[
    {
        "id": "99b13acd3b287f48",
        "type": "tab",
        "label": "Test tunable white light bulb",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "3f69107eea63e2a1",
        "type": "tradfri-light-control",
        "z": "99b13acd3b287f48",
        "gateway": "06a0a469d683c2d3",
        "name": "Tradfri Spot",
        "action": "{}",
        "accessories": [
            ""
        ],
        "groups": [
            "",
            ""
        ],
        "logInputErrors": true,
        "x": 770,
        "y": 320,
        "wires": []
    },
    {
        "id": "323819df4f510759",
        "type": "debug",
        "z": "99b13acd3b287f48",
        "name": "send to light control node",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 810,
        "y": 420,
        "wires": []
    },
    {
        "id": "28377b52576fbbbb",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "cold, bright",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "v": "1",
                "vt": "num"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colorTemperature\":0,\"brightness\":100}",
        "payloadType": "json",
        "x": 190,
        "y": 180,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "b23a1465e1424640",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "neutral, middle",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "v": "1",
                "vt": "num"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colorTemperature\":41,\"brightness\":50}",
        "payloadType": "json",
        "x": 200,
        "y": 220,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "702b283c5334c8e3",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "warm, soft",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "v": "1",
                "vt": "num"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colorTemperature\":100,\"brightness\":25}",
        "payloadType": "json",
        "x": 180,
        "y": 260,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "e0bc6cfe257805c2",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "dark",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "v": "1",
                "vt": "num"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"onOff\":false}",
        "payloadType": "json",
        "x": 170,
        "y": 660,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "c6185d3a89119f97",
        "type": "change",
        "z": "99b13acd3b287f48",
        "name": "Spot A1-A5",
        "rules": [
            {
                "t": "set",
                "p": "topic",
                "pt": "msg",
                "to": "[65550,65551,65552,65553,65554]",
                "tot": "json"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 570,
        "y": 320,
        "wires": [
            [
                "3f69107eea63e2a1",
                "323819df4f510759"
            ]
        ]
    },
    {
        "id": "2226b3c30cf753c4",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "bright",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"brightness\":100}",
        "payloadType": "json",
        "x": 170,
        "y": 540,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "2e0c9fda893f7869",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "middle",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"brightness\":50}",
        "payloadType": "json",
        "x": 170,
        "y": 580,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "098e5d1e3c6f9134",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "soft",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"brightness\":25}",
        "payloadType": "json",
        "x": 170,
        "y": 620,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "1d71db24a31d5707",
        "type": "comment",
        "z": "99b13acd3b287f48",
        "name": "Moods",
        "info": "",
        "x": 150,
        "y": 140,
        "wires": []
    },
    {
        "id": "e32c7de46d42906f",
        "type": "comment",
        "z": "99b13acd3b287f48",
        "name": "brightness",
        "info": "",
        "x": 160,
        "y": 500,
        "wires": []
    },
    {
        "id": "a1ca401374303005",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "cold",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colorTemperature\":0}",
        "payloadType": "json",
        "x": 170,
        "y": 360,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "0e4442bd7e5a13c8",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "neutral",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colorTemperature\":41}",
        "payloadType": "json",
        "x": 170,
        "y": 400,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "4a5260c092651ff3",
        "type": "inject",
        "z": "99b13acd3b287f48",
        "name": "warm",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colorTemperature\":100}",
        "payloadType": "json",
        "x": 170,
        "y": 440,
        "wires": [
            [
                "c6185d3a89119f97"
            ]
        ]
    },
    {
        "id": "6ea94f08409e8335",
        "type": "comment",
        "z": "99b13acd3b287f48",
        "name": "color temperature",
        "info": "",
        "x": 190,
        "y": 320,
        "wires": []
    },
    {
        "id": "06a0a469d683c2d3",
        "type": "tradfri-config",
        "name": "MyHome",
        "gatewayHost": "my-TRADFRI-Gateway.local",
        "identity": "my_tradfri_ID",
        "preSharedKey": "my_key"
    }
]
```
</details>

I'm also looking for some examples how to use the different nodes from this node library.
